### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by zolaemil** [axelberndt/MPM#1]
Hello @axelberndt! This looks very interesting. What are you using this markup for, any particular application it's being used for?

**Comment by axelberndt** [comment]
Hi @zolaemil. This format will be the basis of a series of things we plan in the future - analytical (how do human musicians play music?) as well as productive (humanizing, creating expressive music performances and rendering them into MIDI and audio).

**Comment by zolaemil** [comment]
Thanks!

**Comment by axelberndt** [comment]
Hi @zolaemil, you can find descriptions of the mathematical models behind this format in http://www.cemfi.de/wp-content/papercite-data/pdf/berndt-2015-fem.pdf (this is just a reading sample! full text is published in a book "Works in Audio and Music Technology") and several other papers. What led you here? Do you have a potential application scenario?

**Comment by zolaemil** [comment]
Very interesting! Got here browsing out from MEI-L. At [Tido](https://github.com/tido) we are aligning raw audio with symbolic data, and we have a simple format we use internally for that. The applications you mention sound much more involved.

**Comment by axelberndt** [comment]
If you process MEI you might be interested in another project of mine: [meico](https://github.com/cemfi/meico). This is a converter framework for MEI written in Java. A colleague of mine uses it to generate MIDI, then he generates Chroma features from that. With these, he does audio-to-score(Verovio) alignment. A native Chroma export in meico is also on my todo list.
