### ISSUE TITLE
determine license

### ISSUE THREAD

**Issue by bwbohl** [axelberndt/MPM#2]
There should be a clear statement about the licensing model for the MPM model an schemata.

**Comment by axelberndt** [comment]
CC 3.0

**Comment by bwbohl** [comment]
potentially BY or SA additions?
And why not CC4?
cf.
http://de.creativecommons.org/2013/11/25/version-4-0-ist-da/

**Comment by bwbohl** [comment]
optional BSD or other software license to cover the needs of software developers?

**Comment by axelberndt** [comment]
CC BY 4.0 and BSD 2
