### ISSUE TITLE
introduce gitflow semantic versioning releases

### ISSUE THREAD

**Issue by bwbohl** [axelberndt/MPM#3]
We should rely on gitflow and introduce a master branch as well as tag releases and publish them.

**Comment by axelberndt** [comment]
Continuous integration has been added (many thanks Simon). Any updates should be committed to the ´develop´ branch. Once it reached a release-ready state, make a pull request to the ´master´ branch. Any changes there trigger TravisCI to create a new release with an RNG, DTD, monolithic ODD, and documentation file. The release's version number is read from `mpm.odd`, `<editionStm>`, `<edition>`. Furthermore, the `gh-pages` branch holds the documentation and will be updated automatically, too.

Regarding the versioning, we follow [Semantic Versioning](https://semver.org/). At the time of this writing I work on the schema's reboot that will ultimately become v2.0.0. But while it is in alpha state (i.e. incomplete) I will number it 0.2.x. Sounds a bit confusing but I want to express that the schema is not yet "production-ready".
