### ISSUE TITLE
tempo definitions and application

### ISSUE THREAD

**Issue by bwbohl** [axelberndt/MPM#5]
`tempoStyles` can be defined in `header`, e.g.:

```xml
<tempoStyles>
    <styleDef name="Kajanus">
        <tempoDef name="Andante" value="50"/>
        <tempoDef name="Meno andante" value="100"/>
        <tempoDef name="Allegro molto" value="160"/>
    </styleDef>
</tempoStyles>
```

Applying these definitions will happen in `dated/tempoMap`, e.g.:

```xml
<tempoMap startStyle="Kajanus">
    <tempo date="0" bpm="Andante" beatLength="0.5"/>
    <tempo date="149" bpm="Meno andante" beatLength="0.5"/>
    <tempo date="173" bpm="Allegro molto" beatLength="0.25"/>
</tempoMap>
```

A problem in this concept is that the real tempo results from the combination of the `@bpm` and `@beatLength` values which is only present in the `<tempo>`referencing a certain `tempoDef`. So actually the `tempoDef` does not really define a tempo but only a shorthand for a numeric value.

Moving `@beatLength`to `<tempoDef>` would change this an make it a definition if a real tempo.

**Comment by axelberndt** [comment]
This is exactly how it should work! "Adagio" sais, play it with 50 bpm. And the beat length is a local decision. In one piece it is a quarter note, in another a halfnote.

**Comment by bwbohl** [comment]
Ok I get your point…
I currently am trying to compare tempoMaps of different interpretations.

In order not to duplicate too many features when entering them as separate performances my idea was to enter them as idenpendent styleDefs in the same performance all with the same formal name (derived from the score). 

Then changing the style would just map to the corresponding definition. Maybe I was philologically distracted by trying to enter the exact values as given e.g. half note equals 108 bpm in one example, while the other had quarter note equals 108 bpm. This would not work with the above model. But instead of "transcribing" the given value from a source, I can of course just douple the latter one to half note equals 216.

**Comment by axelberndt** [comment]
Now that MPM v2.0.0 is there let's see how this case could work.

In the `tempoMap` you use element `style` to choose a `styleDef`. Now, in the `tempo` element comes the problem as this defines the `@beatLength`. 
1. The easiest solution is what you proposed with your last sentence, i.e. double the `@bpm` value in the `tempoDef`. This expresses that one performer played the music twice as fast. But this solution does not express that the performer based the tempo on a different note value/beat length.
2. If it is important to express that the two performances are based on a different interpretation of beat length then I suggest editing the `@beatLength` at the corresponding `tempo` elements or even create a second `performance`. The latter comes with quite a lot of duplicate code.

With solution 1 you express that the performers follow the same performance plan, share the same understanding of the performance instructions and only differ in the range of freedom that the instructions leave. Solution 2 says, the performance plans are structurally different even though they happen to use the same terminology, "Adagio". Or in other words: Two different tempi or two different tempo instruction? In which way do the two performers differ?

By the way, the beat length in a tempo instruction has nothing to do with metrical accentuation. The latter depends on time signature, the former does not. A tempo instruction must not necessarily reflect/express in which meter the performers were thinking.
