### ISSUE TITLE
Arpeggiation

### ISSUE THREAD

**Issue by pfefferniels** [axelberndt/MPM#55]
Is there already any feature planned allowing to describe arpeggiation? Especially for the earlier performance practises this is a crucial aspect – and the existing concepts don't seem to suit very well here (`asynchrony`?) ...

As far as I can see, it should be possible to describe: relative position (before the beat by n milliseconds, on the beat etc.) its extent (duration), its direction (upwards, downwards) and its shape (linear, curved in some way – possibly using the same model also used for rubato?). I would be willing to contribute to conception and implementation of such a feature.

**Comment by axelberndt** [comment]
Very interesting suggestion! I added it to the wish list in the Wiki.

You are right, `asynchrony` is not suited for this feature as it shifts the whole `part` instead of just some note onsets.

There is already a rather fiddly way to create arpeggiations via `articulation` using `@absoluteDelay` or `@absoluteDelayMs`. The latter, i.e. the milliseconds modifier `@absoluteDelayMs`, will shift only the note's onset, not its offset! Hence, no need to adjust the duration. Using it would look like this:
```
<articulationMap>
  <articulation date="23450.0" noteid="note1" absoluteDelayMs="-80"/>
  <articulation date="23450.0" noteid="note2" absoluteDelayMs="-60"/>
  <articulation date="23450.0" noteid="note3" absoluteDelayMs="-40"/>
  <articulation date="23450.0" noteid="note4" absoluteDelayMs="-20"/>
</articulationMap>
```

Anyway, there should certainly be a more dedicated way of expressing this kind of feature. Your help with this is very welcome. To start with the conception, 
- Do you know of any theoretical or practical literature describing arpeggio executions? 
- Can you think of further playing techniques that follow a similar logic and can be treated by the same mechanism?
- Is it thinkable that this feature does not only shift the note onsets but also its offsets, e.g. when the hand "rolls" over the keyboard?
- I assume that the last note in an arpeggio is not necessarily on-beat. The arpeggio might even start on-beat. Or it starts before and ends after.
- An arpeggiation might perhaps also have an effect on the note dynamics, probably a relative loudness deviation from the underlying dynamics. It might, for instance, start a bit below the current dynamics level and increase to the last note or vice versa.

What are your thoughts on this?

**Comment by pfefferniels** [comment]
To my knowledge there is hardly any theoretical literature – as far as I  can tell, the most interesting paper is this: Bruno H. Repp, [Some Observations on Pianists' Timing of Arpeggiated Chords](https://journals.sagepub.com/doi/pdf/10.1177/0305735697252004?casa_token=d5bEVAn_XesAAAAA:dsHLsenuQvRi4PHCPlMh6Qgtf3UJ_6fj9gMN0qWcUJiZqh9iPtaR7tsWvGHarxOgv-h0GYzRh03qeLM) (1997).

On a first reading, the central conclusions are probably:
* the most common feature is the lengthening of the final IOI (in accordance with the common function of an arpeggio to prepare and delay a melody note)
* a ritard towards the end is common too, so that e.g. the last two IOI are progressively lengthened
* on the other hand, an _acceleration_ to the penultimate note may take place (so that penultimate IOI is the shortest, while the final IOI is distinctly longer).
* Less frequent is the lengthening of the initial IOI
* There are hardly any other consistent trends ("The high speed of execution probably makes precise temporal shaping difficult and perhaps unnecessary from a perceptual and aesthetic perspective" … perhaps it should be possible to apply randomized imprecision on arpeggio timing?)

For a historical overview Neal Peres da Costas _Off the record_ might be interesting, especially the chapter "Unwritten Arpeggiation".

> Is it thinkable that this feature does not only shift the note onsets but also its offsets, e.g. when the hand "rolls" over the keyboard?

Yes – the beginning of C.P.E. Bachs Württemberg sonata A minor for example is usually performed like that in the right hand (e.g. [here](https://www.youtube.com/watch?v=p9IcjoWrf48)). At the moment I don't know about theoretical descriptions of this phenomenon.

> I assume that the last note in an arpeggio is not necessarily on-beat. The arpeggio might even start on-beat. Or it starts before and ends after.

Yes, that's exactly what I meant – sorry for being unclear :)

The dynamic effect you mention is documented both historically (Lebert and Faisst 1871: "these arpeggios should be simultaneously begun and ended with both hands and should increase in strength from the lowest to the highest tone in each hand, so that the highest tone only attains the power indicated through the signs sf, mf, (afterwards f)", cf. da Costa) as well as empirically (Repp: "… virtually all arpeggios showed a crescendo in the right hand towards the final melody note which – not surprisingly – was played most forcefully.", p. 145)

> Can you think of further playing techniques that follow a similar logic and can be treated by the same mechanism?

Glissando and portamento share the character of stretching out a single event in time, so that it gets a duration, a relative position to the beat and its own dynamic (and temporal) shape …

**Comment by axelberndt** [comment]
Here are some points we talked about regarding the theorization behind arpeggiations.

- We need a naming convention, i.e., unique names to differentiate a "oneshot" arpeggio (every note is played once) from a "continuously repeated" arpeggio (the notes are played multiple times). We will develop a model for the "oneshot" version. The "continuous" version is rather a subject to either tremolo-like techniques or ornamentation; both are rather extensive extensions to MPM not addressed here.
- Arpeggios are played not only by keyboard instruments but also by strings (struck and bowed) and probably also others. How does arpeggio execution differ with these instruments?
- Arpeggiation can be applied to a series of synchronous notes/sound events.
    - In fact, only the onsets are notated at the same time. Durations can differ.
- The note onsets are streched/delayed by the arpeggiation over a certain time, so that they are triggered sequentially
    - highest to lowest or lowest to highest note (more complex variants can be built from those two),
    - the strech can be linear or nonlinear (the power functions from the rubato model could be useful here, too).
    - The amount of strech/delay can be in absolute timing (milliseconds) or in tempo dependent timing (ticks; fast tempo causes fast arpeggio).
- There can be a dynamics gradient so that the notes are played with a crescendo or decrescendo.
    - a relative dynamics change, i.e., it adds to (or subtracts from) the underlying dynamics.
- The note offset dates may 
    - remain unaffected by the arpeggiation or
    - be shifted in parallel with the onset delay (e..g. hand rolls over the keyboard).
- Arpeggiation can be applied to
    - notes in a single staff/part,
    - notes in several staffs,
    - only a subset of notes at the indicated time and staffs (we might use lists of note IDs for this).
    - There can be arpeggiations that apply to only one part and others that apply to several parts in the same score. However, the rule in MPM is, if a part has a local map for a certain feature, that part ignores the global map for that same feature. We wil have to find a way to treat the described situation consistently.

**Comment by pfefferniels** [comment]
Just for clarification: can an arpeggio, that is temporally strongly extended (e.g. with an `absoluteDurationMs` modifier), delay all the following events? Or do we consider that to be a local tempo change?

**Comment by axelberndt** [comment]
### Some results from literature review
Statements from previous posts wil not be repeated.

#### Naming
Continuously performed, rhythmically quantised arpeggios (those that we do not model here)
  - "arpeggio", "metered arpeggiation", Mathena, J. E. (2013). Adapting JS Bach's solo violin Sonatas and Partitas for the marimba: Broken chord and arpeggio performance practices. The University of Southern Mississippi.
  - "linear arpeggio", Brian Cole, “Baroque Performance Practice and the Marimba Transcription,” Percussive Notes (June 1991), 9.
  - "figured arpeggio", Donington, The Interpretation of Early Music, 277-278.
  - "chord arpeggio", David D. Boyden, The History of Violin Playing from its Origins to 1761 and its Relationship to the Violin and Violin Music (London: Oxford University Press, 1965), 330-331.

Oneshot arpeggio/unmetered arpeggiation (the one we want to model here)
  - "broken chord" Mathena, J. E. (2013). Adapting JS Bach's solo violin Sonatas and Partitas for the marimba: Broken chord and arpeggio performance practices. The University of Southern Mississippi.
  - "chordal arpeggio", Brian Cole, “Baroque Performance Practice and the Marimba Transcription,” Percussive Notes (June 1991), 9.
  - "plain arpeggio", Donington, The Interpretation of Early Music, 277-278.

 #### Execution
Mathena (2013) describes a "two-and-two execution" of four-note chords by string instruments. The two lower notes are performed as quasi grace notes. The remaining two are performed on beat. This conflicts with the concept of a continuous function to describe the timing offset of the notes. It is probably a simplification for notation purposes as the players nonetheless have to tilt the bow over the strings. If one really wants to describe this kind of performance it can already be done with the articulation model (with negative delays and duration changes for the grace notes).

Broken chords can be executed with basically four characteristics: up, down, in and out. If we use a list of note IDs to indicate which notes are affected by the arpeggio, we can use the sequence or indicate it with a number to specify the characteristic. If the arpeggio is not associated to specific note IDs it is applied to all notes at the time and in the part, but only with characteristics up and down.

What happens with the preceding note? For a monophonic instrument it must be shortened by the amount of negative delay that the arpeggio introduces. Polyphonic instruments do not have this restriction. We leave it up to the editor to decide this and adapt the preceding note via articulation.

The speed of a broken chord can be absolute (in milliseconds) or tempo dependent (in ticks). In the latter case we can use the tempo and rubato models to refine its timing and, for instance, describe a performer "going out of tempo". However, this might not be sufficient enough. We'll have to see if we can find a more integrated timing distortion aproach that interacts friendly with the tempo and rubato models. Do you have sound examples?

**Comment by axelberndt** [comment]
Here is a bit of target code for the arpeggio integration we want to add to MPM.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://github.com/axelberndt/MPM/releases/latest/download/mpm.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://github.com/axelberndt/MPM/releases/latest/download/mpm.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mpm xmlns="http://www.cemfi.de/mpm/ns/1.0">
    <performance name="a performance" pulsesPerQuarter="720">
        <global>
            <header>
                <ornamentationStyles>
                    <styleDef name="Stylename">
                        <!-- an ornament is a series of transformers -->
                        <ornamentDef name="arpeggio">
                            
                            <!-- the temporalSpread transformer offsets all elements at a given time by a certain amount defined by a power function; the frame attributes are either symbolic or physical but not both (e.g. frame.start OR milliseconds.frame.start) -->
                            <temporalSpread frame.start="-100.0" frame.end="100.0"
                                    milliseconds.frame.start="-200.0" milliseconds.frame.end="200.0"
                                    intensity="1.4"
                                    noteoff.shift="true|false|monophonic"/>
                            
                            <!-- the dynamicsGradient transformer applies relative dynamics deviations to the list of notes affected; the sequence of the list determines the relative position in the linear dynamics function -->
                            <dynamicsGradient transition.from="-1.0" transition.to="1.0"/>
                        </ornamentDef>
                    </styleDef>
                </ornamentationStyles>
            </header>
            
            <dated>
                <ornamentationMap>
                    <style date="0.0" name.ref="Stylename"/>
                    
                    <!-- apply an arpeggio to all notes (listed lowest to highest pitch) at date 0.0 -->
                    <!-- scale is for the dynamics gradient and might be optional with default value 0.0 -->
                    <!-- Direction sets the sequence of notes ordered by in-/decreasing pitch; default is up. What if there are multiple notes with the same pitch? -->
                    <ornament date="0.0" name.ref="arpeggio" scale="20.0" note.order="ascending pitch|descending pitch"/>
                    
                    <!-- apply an arpeggio to the notes listed and in the sequence of the list -->
                    <!-- direction="up" (default) follows the list in the specified sequence; direction="down" follows the list in reverse sequence -->
                    <ornament date="720.0" name.ref="arpeggio" scale="20.0" noteids="id1 id3 id2 id4"/>
                    
                    <!-- Element ornament should be member of model.ornamentDefContent. Needs further consideration. -->
                    <!-- How about grouping of elements? Maybe with brackets in the noteids list (id1 id2) (id3 id4).  -->
                    <!-- If the ornament does not edit but replace the original notes, can I repeat it for a number of times over the ornament time frame? With this I could make an arpeggio into a tremolo only by repeating it. -->
                </ornamentationMap>
            </dated>
        </global>
    </performance>
</mpm>
```

**Comment by axelberndt** [comment]
As of[ MPM v2.1.3](https://github.com/axelberndt/MPM/releases/tag/v2.1.3) arpeggios are part of the ornamentation package.

**Comment by axelberndt** [comment]
This MPM update is by now fully integrated in the API (meico) and MPM Toolbox.
