### ISSUE TITLE
dated information and changes in time signature

### ISSUE THREAD

**Issue by bwbohl** [axelberndt/MPM#6]
Am I correct to assume that changes in time signature will affect the date?
If for example I have two measures 4/4 the dates of the quarter notes would be as follows:

| 1 2 3 4 | 5 6 7 8 |

if instead the second measure is alla breve (2/2) it would be:

| 1 2 3 4 | 5 5.5 6 6.5 |

**Comment by axelberndt** [comment]
No, change of time signature does not affect the date. We have PPQ (pulses per quarter), let's say 360. A quarter stays that long. Time signature does not afffect PPQ.

**Comment by bwbohl** [comment]
ok, I was assuming the date would be in (metrical) beats.

**Comment by bwbohl** [comment]
so the dates with ppq 360 would be 

| 0 360 720 1080 | 1440 1800 2160 2520 |

correct?

**Comment by axelberndt** [comment]
Correct.
