### ISSUE TITLE
define date resolution aka ppq

### ISSUE THREAD

**Issue by bwbohl** [axelberndt/MPM#7]
With `@date`, `@frameLength`, etc. being encoded in MIDI ticks per quarter aka pulses per quarter there should be a global definition of the applicable resolution, either on file or performance level.

**Comment by axelberndt** [comment]
True. In MSM I use this one in global header: `<pulsesPerQuarter ppq="720"/>`. 
We should have this in MPM, too.

**Comment by axelberndt** [comment]
´@pulsesPerQuarter´ is added to the ´performance´ elements.
